### ISSUE TITLE
Make highlighted tabs better recognisable

### ISSUE THREAD

**Issue by aleho** [gnome-integration-team/firefox-gnome#291]
Right now when content in an inactive tab has changed, it only gets a hardly visible bar at the bottom.

It might be my setups to blame, but I can't see that on any monitor I use. A fully coloured background would be easier to identify.

**Comment by seleznev** [comment]
Current look:
![tab-titlechanged](https://cloud.githubusercontent.com/assets/1687481/8766361/39031db6-2e4e-11e5-8836-d33767bd9708.png)
