### ISSUE TITLE
Settings in German

### ISSUE THREAD

**Issue by postblue** [gnome-integration-team/firefox-gnome#301]
Since the 34.1 version of GNOME Theme tweak, the settings are in German, neither in English (if it's a fallback), nor in French (the language is use).

![](http://i.imgur.com/WB1w0vN.png)

**Comment by synapsos** [comment]
This has been fixed in 9a23c185af1dab46f5d2786b032e52dc67f16fa3, I don't know if @garrett will release a fix to Mozilla before 35 is due.
For now you can use the [current build](https://www.dropbox.com/s/5hff1lc1v4309pi/gnome-firefox-theme.xpi?dl=0).

**Comment by postblue** [comment]
Oh, thanks. It would be great for v34 users to have a bugfixed version.

**Comment by seleznev** [comment]
So sorry for this bug. :(
