### ISSUE TITLE
Firefox 39

### ISSUE THREAD

**Issue by mcanders** [gnome-integration-team/firefox-gnome#317]
I am using the GTK3 build of firefox 39 and this addon no longer works.  Are there plans to support it?

**Comment by chpii** [comment]
Author and collaborators seem to be busy to notice.

As far as I can tell we need just "max-version" bump: #318

**Comment by mcanders** [comment]
Can confirm that #318 works

**Comment by seleznev** [comment]
> GTK3 build of firefox 39
> Are there plans to support it?

Nope. We support only official Mozilla's build.

// I think #318 helped you and we can close this issue now.
