### ISSUE TITLE
browser.newtabpage.columns preference

### ISSUE THREAD

**Issue by drxspace** [gnome-integration-team/firefox-gnome#322]
Seems to me the theme doesn't obey the browser.newtabpage.columns preference.

Thanks

**Comment by seleznev** [comment]
Please provide more details about yours problem, because I can't reproduce them. Steps to reproduce and screenshots can help I think.

![screenshot from 2015-04-13 23-24-54](https://cloud.githubusercontent.com/assets/1687481/7121217/6e362abe-e22c-11e4-950c-11c839247dbf.png)

**Comment by Koekelas** [comment]
Default theme
![default](https://cloud.githubusercontent.com/assets/6143998/7146152/bfb83ec0-e2f1-11e4-8110-2420975cec73.png)

Gnome theme
![gnome](https://cloud.githubusercontent.com/assets/6143998/7146155/c9ff3c80-e2f1-11e4-8baa-7ee1841855ad.png)

about:config
![about config](https://cloud.githubusercontent.com/assets/6143998/7146159/ce94fcc6-e2f1-11e4-8a2c-a6dc14eb5081.png)

Firefox 40.0a1 (2015-04-13)
Gnome theme/extension: build from Git, last commit was 97fc3d03f32f2d507fddac53867ddbf573591645

If you need more information, let me know.

**Comment by drxspace** [comment]
Yes exactly that's my issue, thank you @Koekelas

**Comment by seleznev** [comment]
@drxspace, can you provide yours Firefox version? I can reproduce this issue with Fx 38.0b+ only.

**Comment by drxspace** [comment]
Right now I'm using the 39.0a2 version and this exists. A way that I found as a workaround is to set the browser.newtabpage.columns preference to (value_that_i_want + 1)

**Comment by seleznev** [comment]
Well, I can't reproduce this bug anymore => closed.

Please reopen if you still have the issue.
