### ISSUE TITLE
How to create a dark theme compliant with GNOME's dark theme?

### ISSUE THREAD

**Issue by martensms** [gnome-integration-team/firefox-gnome#324]
Hey guys,

I just built the extension and tried to modify it to match the dark theme.
Is there a way to get it properly working with the dark mode? If not, where do I need to look at to tweak it for that purpose?

**Comment by seleznev** [comment]
I'm sorry, I don't understand.

> the extension

GNOME Theme Tweak extension?

> tried to modify it to match the dark theme

What you did?

**Comment by pganuza** [comment]
Hello. I am using Fedora 22 with global dark theme activated in gnome-tweak-tool, which makes Firefox buttons barely visible. This did not happen with Fedora 21, as global dark theme option seem to not affect firefox, which kept the light color scheme. Is this a know issue?
See screenshot at: ![captura de pantalla de 2015-05-14 10-27-24](https://cloud.githubusercontent.com/assets/2458157/7628522/a47aa838-fa24-11e4-943c-f3c2cf7f934e.png)

**Comment by martensms** [comment]
I have the same issues on UbuntuGNOME as in @pganuza's screenshot.

@seleznev I tried to modify the theme (css) to match the dark theme more accurately. Most issues were that I didn't understand the relations of defaults vs. dark theme. The setting I changed in order to have the dark variant (couldn't find it in the browser) was setting [this dark-variant flag to 1](https://github.com/gnome-integration-team/firefox-gnome/blob/master/extension/include/DefaultPrefs.js#L13).

But then, pretty much everything was fucked up. So my initial question was something like "where is the CSS and where are all files required that style the menus (color/background/etc.)?" because I only found the svg files already.

**Comment by plsng** [comment]
It's a hidden setting in about:config, "extensions.gnome-theme-tweak.dark-variant".

**Comment by pganuza** [comment]
Thanks! That solved it. Someone might consider not hiding it :p

**Comment by McSinyx** [comment]
Thanks for revealing the hidden config. However, the dark variant have some problem with icon text and icons (too low contrast - see screeenshots).

![2015-07-13-205300_1280x800_scrot](https://cloud.githubusercontent.com/assets/13689192/9132377/424643b6-3d1d-11e5-969d-4a4d69c44973.png)
![2015-07-19-110508_1280x800_scrot](https://cloud.githubusercontent.com/assets/13689192/9132608/fb94cd96-3d1e-11e5-91ab-9bca03a43686.png)

I'm on Iceweasel 38.1.0

**Comment by hotoiledgoblinsack** [comment]
@pganuza IIRC Fedora 22 has started shipping the GTK3 builds of Firefox (probably to help test them), which are still a WIP and will probably be shipped to stable around Firefox 42 or 43. Progress can be monitored here [1]. The dark theme that GNOME allows switching to from GNOME Tweak Tool is a variant on the GTK3 theme, thus the default Firefox (which still uses GTK2) will not be affected by the GTK3 theme.

Hope this helps.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=627699

**Comment by Gwend4l** [comment]
Thanks for the option  `extensions.gnome-theme-tweak.dark-variant`, that looks really great once activated.

**Comment by hrvstr** [comment]
The about:config setting "extensions.gnome-theme-tweak.dark-variant" was removed with the latest update. It now relies on dark-mode being enabled system-wide.

I use elementary OS (0.3.1 freya) with Firefox stable (42.0) and have dark-mode enabled via elementary tweaks. The Firefox theme doesn't switch to dark-mode tho.

Does anybody have a workaround for this?

**Comment by Gwend4l** [comment]
Same problem as  hrvstr, no more dark firefox :(

**Comment by Mivey** [comment]
I have the same problem as hrvstr and Gwend4l, that dark-mode no longer works. I am using ubuntu GNOME 15.10 (x64), Firefox 42.0 and GNOME Tweak 42.1 and GNOME Theme 42.1. Also the shell in question is GNOME 3.16.

**Comment by acabal** [comment]
I noticed the dark theme broke in Ubuntu 15.10 too--looks like the about:config value is no longer being respected.

Can we bring the gtk2 dark theme back?  I know the goal is to move to gtk3, but Ubuntu moves slowly and we could be stuck waiting as long as another 6 months to a year for them to ship a gtk3 build of Firefox.  That's a long time to go without a nice dark theme :)

**Comment by seleznev** [comment]
We have no way to force usage dark theme anymore. You should have a dark GTK+ theme.
