### ISSUE TITLE
Nightly/41.0 support

### ISSUE THREAD

**Issue by xasx** [gnome-integration-team/firefox-gnome#328]
Firefox 41.0a1 has landed.

Up to 40.0a1, there's has been *no issue* with this theme/extension. Now it shows up as unsupported (breaking API changes?).

Is there anything to do about it?

**Comment by garrett** [comment]
Please try out: https://github.com/gnome-integration-team/firefox-gnome/releases/tag/38.1

**Comment by xasx** [comment]
Thanks. Working. :sun_with_face:
