### ISSUE TITLE
Support for 38.0.1

### ISSUE THREAD

**Issue by DoctorJellyface** [gnome-integration-team/firefox-gnome#329]
The extension from the addons page fails to install. I have yet to try installing it with the max version changed, but I doubt anything will break.

**Comment by Blackrush** [comment]
+1

**Comment by Sesivany** [comment]
:+1:

**Comment by rkmax** [comment]
:+1:

**Comment by garrett** [comment]
Version 38.1 of the theme has been released on GitHub:
https://github.com/gnome-integration-team/firefox-gnome/releases/tag/38.1

It also has been submitted to Mozilla, so it should hopefully show up there soon.

**Comment by garrett** [comment]
(We should probably leave this issue open until Mozilla displays the new version, JFWIW.)

**Comment by almereyda** [comment]
Thanks for the quick release; I've just updated my Fedora and almost cried; fortunately found this immediately. Good work. Calm eye candy we say.

**Comment by Blackrush** [comment]
@garrett works great :+1:

**Comment by meshy** [comment]
Thanks for the fix -- it's now available from Mozilla.

**Comment by DoctorJellyface** [comment]
Cool! Thanks.
