### ISSUE TITLE
Some icons look very out of place

### ISSUE THREAD

**Issue by purpleidea** [gnome-integration-team/firefox-gnome#330]
Great work, but I hope you don't mind a suggestion for improvement.

Some icons such as the + / - zoom icons that people commonly add to their toolbars look *very* out of place with this extension. Try adding the zoom widget to your toolbar to see. It would be great if this all looked as beautiful as epiphany, but with the functionality, speed and stability of firefox.

Actually, if you could theme firefox so it looks exactly like epiphany, and that would be awesome!

As an aside, stock gnome-keyring support in firefox would be great!

Cheers!

**Comment by plsng** [comment]
The zoom icons look pretty good to me when put in the toolbar, in what way do they look out of place to you?

You can make this look even more like Epiphany by following the steps here: https://github.com/chpii/headerbar

Also, for keyring integration: https://addons.mozilla.org/firefox/addon/gnome-keyring-integration-1/

**Comment by seleznev** [comment]
> Some icons such as the + / - zoom icons that people commonly add to their toolbars look very out of place with this extension. Try adding the zoom widget to your toolbar to see.

Okay... And how this buttons should look?

Current look:

![screenshot from 2015-05-20 21-57-22](https://cloud.githubusercontent.com/assets/1687481/7730291/d70d0f9e-ff32-11e4-877d-5849641a5de8.png)
