### ISSUE TITLE
Style issues in 40.0a2

### ISSUE THREAD

**Issue by baco** [gnome-integration-team/firefox-gnome#332]
Some icons or decorations are not centered correctly within their corresponding buttons on Firefox 40.0a2.
![screenshot from 2015-05-25 16 41 59](https://cloud.githubusercontent.com/assets/102958/7801677/028e0644-02ff-11e5-8a92-9f0419571784.png)
![screenshot from 2015-05-25 16 42 29](https://cloud.githubusercontent.com/assets/102958/7801681/0ff7ab8c-02ff-11e5-9f44-b1a28554c966.png)

**Comment by seleznev** [comment]
Fixed. :)
