### ISSUE TITLE
Theme looks out of place on Fedora 22

### ISSUE THREAD

**Issue by kostich** [gnome-integration-team/firefox-gnome#333]
Fedora 22 Workstation, Gnome 3.16.2, Firefox 38.0.1 (built with gtk3 libs, it seems).

The "options" bar bellow the titlebar is dark gray and looks out of place when the global dark theme is turned on for gtk3 apps (see the attached pic). Could you provide a dark theme for gtk3 Firefox or override dark colors with the "light" ones when the global dark theme is turned on?

![2015-05-26 20-26-26](https://cloud.githubusercontent.com/assets/4953862/7820189/f9d9072c-03e6-11e5-987e-d47fd2302643.png)

**Comment by seleznev** [comment]
#325
