### ISSUE TITLE
Empty Button for Pocket scince 38.0.5

### ISSUE THREAD

**Issue by jlp2** [gnome-integration-team/firefox-gnome#335]
Scince the last Update there is an empty button. Seemed that this is the new Pocket integration.
![pocket](https://cloud.githubusercontent.com/assets/12743862/7979354/bfd2385a-0a9e-11e5-9000-56e4cd99fc44.jpg)

**Comment by seleznev** [comment]
It should be fixed by 6f6dbc0:

![screenshot from 2015-06-29 01-04-24](https://cloud.githubusercontent.com/assets/1687481/8397829/834ae564-1df2-11e5-9d1d-7811fc27590f.png)


I'm sorry for epic delay.
