### ISSUE TITLE
TST titlechanged styling needs adjustment

### ISSUE THREAD

**Issue by heftig** [gnome-integration-team/firefox-gnome#342]
The titlechanged styling is currently rather poor, with a bit of glow visible but excluded by the padding.

The glow is also applied to non-pinned tabs, which the default theme does not do.

**Comment by synapsos** [comment]
I am testing the "bubbles" from #291, what do you think?
![light-bubble](https://cloud.githubusercontent.com/assets/107189/8640595/5d4b8cbc-28fe-11e5-8031-c75a559ea118.png) ![dark-bubble](https://cloud.githubusercontent.com/assets/107189/8640596/60cd8bce-28fe-11e5-88d4-2d988803a472.png)

**Comment by heftig** [comment]
Much better!

**Comment by seleznev** [comment]
Fixed in 93a36a7.

@synapsos, please review the commit too.

**Comment by archdria** [comment]
Just a quick offtopic question to @synapsos 
How did you get that space between back/forward buttons and the location bar ?
I had to install 'Classic Theme Restorer', 'NoUn Buttons' and play with stylish.
I got a pretty nice result, but I was wondering if that was feasible within the theme.

Thanks and sorry for the noise...
![screenshot from 2015-08-02 23-02-51](https://cloud.githubusercontent.com/assets/1671644/9028011/a810b53e-396a-11e5-85fe-bd9019ff904b.png)

**Comment by d9h02f** [comment]
https://github.com/chpii/Headerbar/blob/master/README.md

**Comment by archdria** [comment]
Thank you! I think I got a more GNOME-ish look with my config, though...

**Comment by d9h02f** [comment]
You can always submit a pull request!
