### ISSUE TITLE
Active tree tabs styled like regular selected tabs

### ISSUE THREAD

**Issue by heftig** [gnome-integration-team/firefox-gnome#346]
The currently active (but not selected) TST tab is styled like a selected tab on the regular tab bar: Slightly darker, with a thick blue bottom border.

The active tab can only be different from the selected tab when e10s is enabled. When switching tabs it lags behind quite often, but mostly lasts only a split-second. Longer delays appear when the content process is busy rendering other tabs.

**Comment by synapsos** [comment]
@heftig Can you test if d8df8eb85b958c72677d20e54fb1f750a5d6b8fe fixes your responisiveness issues?

**Comment by heftig** [comment]
While the styling is fine now, responsiveness is worse. While it's lagging, there is no longer an immediate feedback when selecting a tab.

Since the default theme has the same issue, I guess this is par for the course.
