### ISSUE TITLE
highlighted tabs not working

### ISSUE THREAD

**Issue by wshuman3** [gnome-integration-team/firefox-gnome#348]
I believe the titlechanged.svg file was missing from commit 442d82134b341b173548c0513b3a46b487ebd967 which changed the style of highlighted tabs.

**Comment by seleznev** [comment]
No, I commited it into master: https://github.com/gnome-integration-team/firefox-gnome/blob/master/theme/shared/browser/tabbrowser/titlechanged.svg

Can you try this userstyle?:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

@-moz-document url("chrome://browser/content/browser.xul") {

  .tab-content[pinned] .tab-icon-overlay {
    display: -moz-box;
    list-style-image: url("chrome://browser/skin/tabbrowser/titlechanged.svg");
  }

}
```

Also, please provide more details about yours environment: OS, version of Firefox, installed extensions.

**Comment by wshuman3** [comment]
So I guess I misunderstood how the functionality worked until looking at the code and some other issues logged with mozilla.  I read the initial issue #291 and expected the icon to appear on content change, but it only appears on title change.  I created quick test and that functionality is working as expected.  Sorry for the waste in time.
