### ISSUE TITLE
GNOME Theme Tweak not compatible with Firefox 39+

### ISSUE THREAD

**Issue by Ri100** [gnome-integration-team/firefox-gnome#352]
When you try to install the GNOME Theme Tweak add-on from https://addons.mozilla.org/en-US/firefox/addon/gnome-theme-tweak/ you get:
"This add-on is not compatible with your version of Firefox."
Install anyway will also not work.

**Comment by synapsos** [comment]
Our release 40.1 is only compatible with Firefox 40 and higher, which is slated to come out next Tuesday. You can find the old release [here](https://addons.mozilla.org/en-US/firefox/addon/gnome-theme-tweak/versions/).

**Comment by seleznev** [comment]
Thanks! :+1:
