### ISSUE TITLE
User Agent Switcher addon's button does not have border

### ISSUE THREAD

**Issue by kostich** [gnome-integration-team/firefox-gnome#353]
[User Agent Swticher](https://addons.mozilla.org/en-us/firefox/addon/user-agent-switcher/) addon's button does not have border when it's placed in the toolbar and when the option "Relief buttons on the navigation toolbar" option is checked via Gnome Theme Tweak extension.

 ![Image of the issue](http://www.dodaj.rs/f/44/zL/145I7VVj/---2015-08-10-14-39-50.png)

**Comment by synapsos** [comment]
The toolbarbutton is missing `class="toolbarbutton-1` (addon has not been updated in 4 years). 
I recommend installing [User Agent Overrider](https://addons.mozilla.org/firefox/addon/user-agent-overrider/) instead so we don't have to implement an exception for this outdated addon. I hope I could help.

**Comment by kostich** [comment]
Thank you for your suggestion. I agree, using this other addon is a better solution.
