### ISSUE TITLE
Scrollbar clickable area does not touch window edge

### ISSUE THREAD

**Issue by heftig** [gnome-integration-team/firefox-gnome#354]
The clickable area of the scrollbar does not touch the window edge. This is a usability problem when the window is maximized.

**Comment by seleznev** [comment]
1. Can you provide more details about yours environment: OS, Firefox version, toolkit?
2. Can you try to reproduce it with the default theme?

**Comment by heftig** [comment]
Linux, Firefox 41.0a2 and 42.0a2, GTK3.
Default theme is fine.

**Comment by seleznev** [comment]
I can't reproduce it on Firefox 41.0b7 (this version uses GTK2):

![screenshot from 2015-09-05 17-14-11](https://cloud.githubusercontent.com/assets/1687481/9698991/4d51eff2-53e9-11e5-9778-6cf1a956effe.png)

**Comment by heftig** [comment]
Turns out this is a Firefox problem. Sorry.
