### ISSUE TITLE
Scrollbar slider should remain blue while dragging

### ISSUE THREAD

**Issue by heftig** [gnome-integration-team/firefox-gnome#355]
Currently, the slider returns to the default color while getting dragged. It should be blue to match the Adwaita scrollbars.

**Comment by seleznev** [comment]
It works fine on current Beta builds from [mozilla.org](http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/):
![screenshot from 2015-08-11 21-09-28](https://cloud.githubusercontent.com/assets/1687481/9201177/1208c9c6-4065-11e5-8ac0-e8885a7f2850.png)

I have this issue on Nightly builds (with GTK3) but it isn't bug in our theme. If you use Fedora / Nightly, you should report this issue to upstream developers.

**Comment by heftig** [comment]
Right. Sorry.
