### ISSUE TITLE
'Sync' Avatar Support & Other UI Issues in Firefox Menu

### ISSUE THREAD

**Issue by jdorenbush** [gnome-integration-team/firefox-gnome#356]
**Sync Avatar**
If you don't have a Sync avatar, a sync icon (disproportionately-sized) is displayed where the avatar would be displayed in the Firefox Menu.
![screenshot](https://cloud.githubusercontent.com/assets/7949554/9248639/4b7eb37e-4172-11e5-871f-b2399d1b5b79.png)

If you do have an avatar, most of the image is cropped out so you'll only see a tiny corner of it.
![screenshot-avatar](https://cloud.githubusercontent.com/assets/7949554/9248643/561671be-4172-11e5-9561-c2240f75e435.png)

**Panel Width**
The width of the Sync panel should span the entire width of the Firefox Menu. Currently it looks like it's about 40-50%. This is most noticeable with the top border. It's also noticeable when hovering over the panel because the hover affect only changes a portion of the background color.

**Hovering over Username**
The background color when hovering over the username is the wrong color, but the username shouldn't even have it's own hover affect. The username and the panel act as a single button and the hover affect needs to accurately represent that: there shouldn't be any visible change when moving the mouse from hovering over the panel to just hovering over the username.
![screenshot-username](https://cloud.githubusercontent.com/assets/7949554/9248650/6796504e-4172-11e5-8317-277216727fb6.png)

**Comment by seleznev** [comment]
What version of Firefox you use?

**Comment by jdorenbush** [comment]
41.0b1

**Comment by seleznev** [comment]
It should looks fine since [the 41.1b1 theme version](https://addons.mozilla.org/en-US/firefox/addon/adwaita/versions/41.1b1):

![screenshot from 2015-09-05 17-06-47](https://cloud.githubusercontent.com/assets/1687481/9698969/6d71e144-53e8-11e5-9a24-b8001f7534ca.png)

Please reopen the issue if the problem still exists.
