### ISSUE TITLE
Security popup broken in firefox 41.0 and up

### ISSUE THREAD

**Issue by bartlibert** [gnome-integration-team/firefox-gnome#357]
In the beta and aurora releases, the "security popup" has changed, and it is broken with the gnome integration theme.

The popup now exists of two stages, first a generic one:
![tooltip_001](https://cloud.githubusercontent.com/assets/948770/9327927/9fe2eee0-45a4-11e5-81ba-82b47a3c6bfe.png)
If you click on the ">", you get some more information.
![tooltip_002](https://cloud.githubusercontent.com/assets/948770/9327926/9fdf2508-45a4-11e5-8275-8a1e36345871.png)

With the gnome theme, the first stage looks bad, but also contains all possible "security" states, instead of just the correct one ("secure" in this case):
![tooltip_003](https://cloud.githubusercontent.com/assets/948770/9327929/9febd58c-45a4-11e5-9953-035b3f215973.png)
Clicking on the huge square button does yield a second part, but, again, all possible states are shown, instead of only the correct one:
![tooltip_004](https://cloud.githubusercontent.com/assets/948770/9327930/9fed423c-45a4-11e5-828b-93768c11801b.png)

**Comment by seleznev** [comment]
It's fixed now. You can install [the beta version](https://addons.mozilla.org/en-US/firefox/addon/adwaita/versions/41.1b1) if you want to test it.

Thank you for notice!

**Comment by bartlibert** [comment]
I can confirm it is ok in 41, but it seems broken again in recent 42 builds. I don't know if you prefer to re-open this issue or should I create a new one?

**Comment by seleznev** [comment]
Reopen seems better, but we will fix it after rebase on Fx 42.

**Comment by seleznev** [comment]
Fixed in 42.1 => closed.
