### ISSUE TITLE
Add-ons Overview Page partially  broken

### ISSUE THREAD

**Issue by stonerl** [gnome-integration-team/firefox-gnome#358]
![screenshot from 2015-08-18 18-21-12](https://cloud.githubusercontent.com/assets/2091312/9335769/444e3418-45d6-11e5-8dd5-a34bcf789b07.png)

Firefox 40.0 on Fedora 22 with Gnome 3.16

**Comment by seleznev** [comment]
Can you try [the latest version](https://addons.mozilla.org/en-US/firefox/addon/adwaita/versions/?page=1#version-40.1)? It should looks fine.

**Comment by seleznev** [comment]
Original issue: #332

**Comment by stonerl** [comment]
Is it supposed to look like the standard theme now?

![screenshot from 2015-08-18 18-32-10](https://cloud.githubusercontent.com/assets/2091312/9336047/b1d85620-45d7-11e5-8e13-e85aa51f503a.png)

**Comment by seleznev** [comment]
Yep.

**Comment by stonerl** [comment]
OK. thanks for the quick reply.
