### ISSUE TITLE
Too high contrast #0000EE against #F57900

### ISSUE THREAD

**Issue by GreenLunar** [gnome-integration-team/firefox-gnome#360]
Viewing an archived MHT page with http://maf.mozdev.org/
Hyperlink color (in blue) is too strong

Info bar color is `#F57900`
Text color is `#0000EE`

**Comment by seleznev** [comment]
It should looks fine now:

![screenshot from 2015-08-20 23-53-41](https://cloud.githubusercontent.com/assets/1687481/9391083/5562318c-478e-11e5-98ab-6ba621adf38a.png)

**Comment by GreenLunar** [comment]
Please undo this commit.  I thought the fix is would be a general one, not a specific one.

If specific code is required, Mozilla needs to enhance its API, and when that would occur I would probably be migrating Midori and QupZilla.

**Comment by seleznev** [comment]
Commit will not be reverted because the notification looks better then before.

**Comment by GreenLunar** [comment]
This is true, but one line of extension-specific code is too much.  This is not a task that theme makers should do.

Anyway, thank you for the fix.
