### ISSUE TITLE
gnome-theme-tweak disabled in Firefox 40.0.3

### ISSUE THREAD

**Issue by cpatrick08** [gnome-integration-team/firefox-gnome#364]
It says Gnome Theme Tweak could not be verified for use in Firefox and has been disabled. The problem is due to Firefox Signing requirements for Firefox addons, see https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct on how to sign your addons.

**Comment by cpatrick08** [comment]
Got it to work from the Releases github version, but it will need to be signed or it won't work on Firefox 41+

**Comment by seleznev** [comment]
> Add-ons installed through the official Firefox Add-ons site undergo a rigorous review process before they are published. These add-ons are verified and signed.

https://addons.mozilla.org/firefox/addon/gnome-theme-tweak/
