### ISSUE TITLE
Close button disappear on fullscreen using htitle

### ISSUE THREAD

**Issue by dyskette** [gnome-integration-team/firefox-gnome#370]
Normal window, before fullscreen.
![captura de pantalla de 2015-10-06 10-33-58](https://cloud.githubusercontent.com/assets/6687927/10313574/f3c27444-6c15-11e5-8ed1-72039469df64.png)

When entering fullscreen, the restore button is drawn on the tab bar, and of course the close button disappears.
![captura de pantalla de 2015-10-06 10-34-39](https://cloud.githubusercontent.com/assets/6687927/10313573/f3bec34e-6c15-11e5-9fd7-122bb90db00f.png)

After exiting fullscreen, the restore button disappear and the close button is gone too.
![captura de pantalla de 2015-10-06 10-35-06](https://cloud.githubusercontent.com/assets/6687927/10313575/f3c79cbc-6c15-11e5-8317-81fedbb4876a.png)

firefox 41.0.1 on fedora 23 from repos.
firefox-gnome theme and extension built from git.
htitle 3.4.1 from mozilla website.

**Comment by seleznev** [comment]
It's bug in HTitle, not in GNOME Theme. But it should be fixed in any way, Thank you for report!
