### ISSUE TITLE
Dark menu icon in dark theme with Firefox 42

### ISSUE THREAD

**Issue by emersion** [gnome-integration-team/firefox-gnome#374]
![screenshot from 2015-11-03 18-05-18](https://cloud.githubusercontent.com/assets/506932/10915086/799da1ec-8255-11e5-93be-12238955c8fb.png)

**Comment by seleznev** [comment]
We removed `extensions.gnome-theme-tweak.dark-variant`  key in version for Firefox 42. So, it should works fine with the [latest version](https://addons.mozilla.org/en-US/firefox/addon/adwaita/versions/42.1).

**Comment by emersion** [comment]
So, how to enable the dark theme?

**Comment by seleznev** [comment]
It will be enabled automatically if you use dark GTK+ theme.

**Comment by emersion** [comment]
:+1:

**Comment by emersion** [comment]
Well, I have the dark GTK+ theme enabled for all apps, but Firefox has still a light theme...

**Comment by seleznev** [comment]
@emersion, looks like you use Firefox on GTK2. To check it open the Browser console and paste following code to command line:
```
Components.classes["@mozilla.org/xre/app-info;1"].getService(Components.interfaces.nsIXULRuntime).widgetToolkit;
```

---

![screenshot from 2015-11-08 19-56-52](https://cloud.githubusercontent.com/assets/1687481/11020729/817a0240-864a-11e5-8062-8708107792da.png)

---

We have no way to force using dark theme in Firefox anymore. You really need a dark GTK+ theme to enable it.

**Comment by emersion** [comment]
Excuse me, one last question: how to use GTK3 in Firefox ? By using Firefox Dev Edition ?

**Comment by seleznev** [comment]
> how to use GTK3 in Firefox ? By using Firefox Dev Edition ?

Firefox Beta from [ftp.mozilla.org](http://ftp.mozilla.org/pub/firefox/releases/) should works well too. Looks like it's best way now. :(
