### ISSUE TITLE
Sync options are not displayed in FF42

### ISSUE THREAD

**Issue by RaphaelRochet** [gnome-integration-team/firefox-gnome#375]
In preferences, the Sync section is empty. (Switching to default theme bring it back.)

![capture du 2015-11-04 19-18-03](https://cloud.githubusercontent.com/assets/1675389/10947552/d0e0e8c8-8328-11e5-8ee7-6a88459969c4.png)

Using FF42 on Arch

**Comment by seleznev** [comment]
Can you try [latest version on AMO](https://addons.mozilla.org/en-US/firefox/addon/adwaita/versions/42.1)? It should look fine with it.

**Comment by RaphaelRochet** [comment]
Awesome. Thanks !!!
