### ISSUE TITLE
Too big extension-icons in ff 42.0

### ISSUE THREAD

**Issue by fabsmusicjunkie** [gnome-integration-team/firefox-gnome#376]
since firefox 42.0, some of the extension-icons are shown way too big

**Comment by fabsmusicjunkie** [comment]
fixed in the new version

**Comment by simonbcn** [comment]
Same problem on Firefox 44:
![seleccion_001](https://cloud.githubusercontent.com/assets/428231/12943204/065edfba-cfe0-11e5-916e-55dbcaa6f432.png)

**Comment by synapsos** [comment]
@simonbcn 
This is an issue with those specific addons, their buttons do not have the attribute `constrain-size: true`. I send an email with the fix to the dev, hopefully he updates soon. In the meantime you can use my [patched versions](https://github.com/gnome-integration-team/firefox-gnome/files/125543/patched_gkeeppanel_intgcal.zip).

Let me know if there are any other addons with this issue.

**Comment by simonbcn** [comment]
But with other themes this doesn't occur.

**Comment by synapsos** [comment]
> But with other themes this doesn't occur.

You are right, it is not happening in default theme. I am going to merge the new theme files for Firefox 44+ and see what they changed.
