### ISSUE TITLE
Certificate popup is completely messed up

### ISSUE THREAD

**Issue by moimael** [gnome-integration-team/firefox-gnome#378]
When clicking on the certificate icon in https url, the popup windows is completely messed up.

**Comment by seleznev** [comment]
Can you try ]latest version on AMO](https://addons.mozilla.org/en-US/firefox/addon/adwaita/versions/42.1)? It should look fine with it.

**Comment by corna** [comment]
It works perfectly on my Iceweasel 42.0, thanks
