### ISSUE TITLE
Tabs and relief buttons are light even with dark theme

### ISSUE THREAD

**Issue by zandrmartin** [gnome-integration-team/firefox-gnome#379]
I woke up to this:

![what](https://cloud.githubusercontent.com/assets/7629614/10997633/2e65e1ca-8454-11e5-8ccb-94d0e84f28b1.png)

I have no idea what has happened. As far as I'm aware I didn't do anything that would've caused this.

**Comment by zandrmartin** [comment]
Please disregard, I updated to the new version and that resolved this issue.

**Comment by seleznev** [comment]
Looks like you used GNOME theme 40.1 with GNOME Tweak Extension 42.1.

**Comment by zandrmartin** [comment]
That was indeed the case - somehow one got updated and the other didn't. Everything looks great in the update - it resolved some minor issues I always had. Thanks a bunch!
