### ISSUE TITLE
Page search missing dark theme variant

### ISSUE THREAD

**Issue by nexfwall** [gnome-integration-team/firefox-gnome#383]
When searching on web page and using dark theme option, search bar appears with white Adwaita theme style. I can not even read text on buttons.

Firefox version: 42.0, from Fedora, built with gtk3 by default.

![2015-11-28 12-34-06](https://cloud.githubusercontent.com/assets/8678891/11451205/be1a1202-95cd-11e5-85cc-b975adc3ee92.png)

**Comment by seleznev** [comment]
Screenshot:
![screenshot from 2015-11-28 20-13-28](https://cloud.githubusercontent.com/assets/1687481/11452292/9805856a-9604-11e5-9a6b-cd323fa82777.png)

**Comment by nexfwall** [comment]
But why it do not work for me?

В Сб, 28/11/2015 в 06:17 -0800, Aleksandr Seleznev пишет:

**Comment by seleznev** [comment]
I have no idea. =\
Did you build the theme from the master branch?

**Comment by nexfwall** [comment]
Nope. I am downloaded latest release (42.1) from releases section of
GitHub.

В Сб, 28/11/2015 в 06:50 -0800, Aleksandr Seleznev пишет:
