### ISSUE TITLE
Dark theme applied to tabs content in Firefox 43

### ISSUE THREAD

**Issue by emersion** [gnome-integration-team/firefox-gnome#387]
For example, on some websites inputs' foreground & background are set to white, so text is unreadable.

**Comment by seleznev** [comment]
Can you reproduce the bug with the default Firefox theme?

**Comment by emersion** [comment]
Nope. Here are some screenshots from Facbook & Google+:
![screenshot from 2015-12-19 15-42-13](https://cloud.githubusercontent.com/assets/506932/11913539/6871534c-a667-11e5-9d5d-8f39701f830d.png)
![screenshot from 2015-12-19 15-41-48](https://cloud.githubusercontent.com/assets/506932/11913540/6895f2e2-a667-11e5-9e82-c64d1aca1c51.png)

**Comment by emersion** [comment]
Well, in fact I can reproduce with the default theme. Sorry! This seems a Firefox issue.

**Comment by emersion** [comment]
Here is a workaround: https://wiki.archlinux.org/index.php/Firefox#Unreadable_input_fields_with_dark_GTK.2B_themes
