### ISSUE TITLE
Not compatable with Firefox 43.0.1 with GTK 3

### ISSUE THREAD

**Issue by MrFalcon** [gnome-integration-team/firefox-gnome#388]

**Comment by Distopico** [comment]
+1

**Comment by N0mi5** [comment]
+1

**Comment by genodeftest** [comment]
Works fine on Firefox 44 with Gtk3.

**Comment by coot** [comment]
Works fine here too (Firefox 44 with Gtk3).

**Comment by Distopico** [comment]
The errrors for me is in dark theme variant.

Similar issues: [#386](https://github.com/gnome-integration-team/firefox-gnome/issues/386)

**Comment by genodeftest** [comment]
Which errors do you see? UI elements having incorrect colors is no error, but a malfunction. Unless you can exactly describe what's wrong nobody can help you.

**Comment by MrFalcon** [comment]
I forgot I had made this lol
