### ISSUE TITLE
Style the full screen message

### ISSUE THREAD

**Issue by lumiru** [gnome-integration-team/firefox-gnome#389]
When we use full screen mode ([from Web API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)), a message is shown on top of the screen to notify we can use Esc. key to go out. With the default theme, it looks like that :
![without-gnome-theme](https://cloud.githubusercontent.com/assets/4085705/11969391/47b4f398-a919-11e5-9768-4cf5cb97fc3e.png)

With the Gnome Theme 42.1, there is no style for this message :
![with-gnome-theme](https://cloud.githubusercontent.com/assets/4085705/11969392/47b80d76-a919-11e5-88e6-dad1cf34ddc5.png)

**Comment by Slomo17** [comment]
+1

**Comment by lumiru** [comment]
It seams to be solved.
