### ISSUE TITLE
Scroll bar one pixel away from edge of window

### ISSUE THREAD

**Issue by eduardomezencio** [gnome-integration-team/firefox-gnome#414]
When the firefox window is maximized using firefox-gnome, moving the mouse to the right edge of the screen does not put it over the scroll bar; you have to move one pixel away to be able to click on it. This makes it very slow to use the scroll bar with a mouse, and [Fitts' Law explains it](https://blog.codinghorror.com/fitts-law-and-infinite-width/)

**Comment by d9h02f** [comment]
Works as it should for me.

**Comment by eduardomezencio** [comment]
Works as it should for me now, in firefox 48. I had the problem with 47
