### ISSUE TITLE
Update license (MPL 1.1 -> MPL 2.0)

### ISSUE THREAD

**Issue by seleznev** [gnome-integration-team/firefox-gnome#65]
Source code of a new version of Firefox under MPL 2.0. I think to change license is good idea if you will use this code (for example, styles of dev tools).

**Comment by seleznev** [comment]
> GNOME 3 is now licensed under Mozilla Public License, version 2.0.
> 4 days ago by garrettl

Fixed. :smile:

**Comment by garrett** [comment]
I'm glad that *finally* worked! ☺
